### ISSUE TITLE
problem: --help doesn't display --format options available

### ISSUE THREAD

**Issue by dodpears** [csirtgadgets/cif-sdk-py#124]
.e.g. 

  -f FORMAT, --format FORMAT
                        specify output format [default: table; options: bind, bro, csv, html, json, snort, table]

**Comment by wesyoung** [comment]
do you have examples you're thinking about?

**Comment by dodpears** [comment]
Not sure what you mean "examples" in addition to what I noted in the comment section of the issue. That is, the section of 'cif --help' that currently displays just:
   -f FORMAT, --format FORMAT
    specify output format [default: table]

could display something like:

-f FORMAT, --format FORMAT
specify output format [default: table; options: bind, bro, csv, html, json, snort, table]

**Comment by wesyoung** [comment]
ah, it's not "options" per say, i was confused because --format should show those plugins (but i guess it doesn't in the v2 sdk). i was looking at the v3 client when i saw this [where it does the right thing].

```
$ cif -h
-f {stix,json,snort,csv,bro,bind,table}, --format {stix,json,snort,csv,bro,bind,table}
                        specify output format [default: table]"
```

should be an easy fix.

**Comment by wesyoung** [comment]
this should be on it's way through pypi, so upgrading via:

```
$ pip install cifsdk --upgrade
$ cif -h
```

should work...
