### ISSUE TITLE
permissions error on install

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/cif-sdk-py#78]
the install directions to not say to ```sudo pip install...```

which results in this error:

```
error: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/pytricia.so'

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_giovino/pytricia/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-X4tgUX-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_giovino/pytricia
```

Need to update the install instructions with:

```sudo pip install git+https://github.com/csirtgadgets/py-cifsdk```

**Comment by wesyoung** [comment]
you don't wanna use sudo if you're installing this in a virtualenv...

**Comment by wesyoung** [comment]
actually; what i'm researching is how to get this stuff into packagecloud.io and/or pypi automatically so "for default installs" the instructions are a bit more in-line with pip, although for this specific issue; it will still come up if you're not using sudo to get it into the system tree...

**Comment by giovino** [comment]
two problems:

1. the directions do not lead the person down the virutal env path.. if you follow them verbatim, you get the error I posted. 

2. if you install in a virtualenv.. then the cif command will NOT work on the cli without entering the virutal env right? (source venv/bin/activate)

**Comment by wesyoung** [comment]
https://github.com/dropbox/dropbox-sdk-python

do you see sudo anywhere in there?
